#!/usr/bin/pkexec /bin/bash
set -euo pipefail

if [ ! -f "/etc/apt/sources.list.d/fruitnanny.list" ]; then
    >&2 echo "Error: /etc/apt/sources.list.d/fruitnanny.list not found"
    exit 1
fi

exec /usr/bin/apt update -q \
    --no-list-cleanup \
    -o Dir::Etc::sourcelist="sources.list.d/fruitnanny.list" \
    -o Dir::Etc::sourceparts="-"
