#!/usr/bin/pkexec /bin/bash

# Verify if service exists. Otherwise, the "start --wait" call will block
# indefinitely.
systemctl status fruitnanny-update.service > /dev/null
rc=$?

if [ $rc -eq 4 ]; then
    >&2 echo "Error: service fruitnanny-update.service not found"
    exit 1
fi

exec systemctl start --wait fruitnanny-update.service
