#!/usr/bin/pkexec /bin/bash
set -euo pipefail

if ! systemctl --all --type service | grep -q "nginx.service"; then
    >&2 echo "Error: service fruitnanny-upgrade.service not found" > /dev/stderr
    exit 1
fi

exec systemctl start --wait fruitnanny-upgrade.service
